---
title: "Class Information"
output: 
  html_document:
    theme: sandstone
---

<style type="text/css">


.main-container {
  max-width: 1180px;
}


body{ /* Normal  */
      font-size: 14px;
      text-align: justify;
      text-justify: inter-word;
  }
td {  /* Table  */
  font-size: 10px;
}
h1.title {
  font-size: 30px;
  color: DimGrey;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkGrey;
}
h2 { /* Header 2 */
    font-size: 22px;
  color: DarkGrey;
}
h3 { /* Header 3 */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkGrey;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
<p>

Welcome to IS580 Knowledge Discovery and Mining Tutorials page. This lecture will be given by [Assoc. Prof. Dr. Tugba Taskaya Temizel](https://blog.metu.edu.tr/ttemizel/). The assistant who will be doing the applied portion of the course is Seyma Cavdar. This page will contain the lab codes for the class as RMarkdown documents.You can go to the [github repo](https://github.com/SeymaCavdar/R_for_KnowledgeDiscoveryandMining) for the full Rmarkdown files to use in your local environment. The entirety of materials will be available through ODTUClass. This blog only aims to provide a collection of rendered RMarkdown files.


The syllabus for this year's lecture is as follows:

- Introduction to Data Mining
- Data Preprocessing
- Mining Frequent Patterns, Associations, and Correlations
- Prediction
- Classification (Logistic regression, linear&non-linear classification, neural networks, SVM, linear discriminant analysis, Bayesian classification, k-NN, decision trees, rule-based classification)
- Evaluation and Credibility
- Clustering (Hierarchical, density-based, model-based)
- Combining methods
- Advanced methods
</p>